---
# Tasks for creation of CFSSL config files

- name: Create folder for cfssl config files
  ansible.builtin.file:
    path: "{{ cfssl_config_dir }}"
    state: directory
    mode: "0750"
  tags: k8s_certs_config

- name: Create folder for Kubernetes certificates
  ansible.builtin.file:
    path: "{{ certs_output_dir }}"
    state: directory
    mode: "0750"
  tags: k8s_certs_config

- name: Gather facts about Kubernetes instances
  ansible.builtin.setup:
  delegate_to: "{{ item }}"
  delegate_facts: true
  loop: "{{ groups[k8s_controllers_group] | union(groups[k8s_workers_group]) }}"
  tags: k8s_certs_config

- name: Create list of control plane IP addresses for Kubernetes API server certificate
  ansible.builtin.set_fact:
    k8s_controller_hosts: >
      {% set comma = joiner(",") %}{%- for item in groups[k8s_controllers_group] %}
        {{ comma() }}
        {{hostvars[item].ansible_all_ipv4_addresses | ansible.utils.reduce_on_network( k8s_instances_network ) | first }}{{ comma() }}
      {%- endfor -%}
  tags: k8s_certs_config

- name: Create the CA configuration file
  ansible.builtin.template:
    src: ca-config.json.j2
    dest: "{{ cfssl_config_dir }}/ca-config.json"
    mode: "0750"
  tags: k8s_certs_config

- name: Create the CA CSR file
  ansible.builtin.template:
    src: ca-csr.json.j2
    dest: "{{ cfssl_config_dir }}/ca-csr.json"
    mode: "0750"
  tags: k8s_certs_config

- name: Create the admin CSR file
  ansible.builtin.template:
    src: admin-csr.json.j2
    dest: "{{ cfssl_config_dir }}/admin-csr.json"
    mode: "0750"
  tags: k8s_certs_config

- name: Create the worker CSR files
  ansible.builtin.template:
    src: worker-csr.json.j2
    dest: "{{ cfssl_config_dir }}/{{ item }}-csr.json"
    mode: "0750"
  with_inventory_hostnames:
    - "{{ k8s_workers_group }}"
  tags: k8s_certs_config

- name: Create the Kube Controller Manager CSR file
  ansible.builtin.template:
    src: kube-controller-manager-csr.json.j2
    dest: "{{ cfssl_config_dir }}/kube-controller-manager-csr.json"
    mode: "0750"
  tags: k8s_certs_config

- name: Create the Kube Proxy CSR file
  ansible.builtin.template:
    src: kube-proxy-csr.json.j2
    dest: "{{ cfssl_config_dir }}/kube-proxy-csr.json"
    mode: "0750"
  tags: k8s_certs_config

- name: Create the Kube Scheduler CSR file
  ansible.builtin.template:
    src: kube-scheduler-csr.json.j2
    dest: "{{ cfssl_config_dir }}/kube-scheduler-csr.json"
    mode: "0750"
  tags: k8s_certs_config

- name: Create the Kubernetes API Server CSR file
  ansible.builtin.template:
    src: kubernetes-csr.json.j2
    dest: "{{ cfssl_config_dir }}/kubernetes-csr.json"
    mode: "0750"
  tags: k8s_certs_config

- name: Create the Service Account CSR file
  ansible.builtin.template:
    src: service-account-csr.json.j2
    dest: "{{ cfssl_config_dir }}/service-account-csr.json"
    mode: "0750"
  tags: k8s_certs_config
