---
# Tasks for generating Kubernetes certificates

- name: Generate the CA certificate and private key
  ansible.builtin.shell:
    chdir: "{{ cfssl_config_dir }}"
    executable: /bin/bash
    cmd: >
      set -eo pipefail;
      cfssl gencert -initca ca-csr.json | cfssljson -bare {{ k8s_certs_dir }}/ca
    creates: "{{ item }}"
  loop:
    - "{{ k8s_certs_dir }}/ca.csr"
    - "{{ k8s_certs_dir }}/ca.pem"
    - "{{ k8s_certs_dir }}/ca-key.pem"
  tags: k8s_certs_generate

- name: Generate the admin certificate and private key
  ansible.builtin.shell:
    chdir: "{{ cfssl_config_dir }}"
    executable: /bin/bash
    cmd: >
      set -eo pipefail;
      cfssl gencert \
        -ca=ca.pem \
        -ca-key=ca-key.pem \
        -config=ca-config.json \
        -profile=kubernetes \
        admin-csr.json | cfssljson -bare {{ k8s_certs_dir }}/admin
    creates: "{{ item }}"
  loop:
    - "{{ k8s_certs_dir }}/admin.csr"
    - "{{ k8s_certs_dir }}/admin.pem"
    - "{{ k8s_certs_dir }}/admin-key.pem"
  tags: k8s_certs_generate

- name: Generate the worker node certificates and private keys
  ansible.builtin.shell:
    chdir: "{{ cfssl_config_dir }}"
    executable: /bin/bash
    cmd: >
      set -eo pipefail;
      cfssl gencert \
        -ca=ca.pem \
        -ca-key=ca-key.pem \
        -config=ca-config.json \
        -hostname={{ hostvars[item]['ansible_hostname'] }},{{ hostvars[item]['ansible_all_ipv4_addresses'] | ansible.utils.reduce_on_network( k8s_instances_network ) | first }} \
        -profile=kubernetes \
        {{ item }}-csr.json | cfssljson -bare {{ k8s_certs_dir }}/{{ item }}
    creates: "{{ k8s_certs_dir }}/{{ item }}-key.pem"
  with_inventory_hostnames: "{{ k8s_workers_group }}"
  tags: k8s_certs_generate

- name: Generate the Kube Controller Manager certificate and private key
  ansible.builtin.shell:
    chdir: "{{ cfssl_config_dir }}"
    executable: /bin/bash
    cmd: >
      set -eo pipefail;
      cfssl gencert \
        -ca=ca.pem \
        -ca-key=ca-key.pem \
        -config=ca-config.json \
        -profile=kubernetes \
        kube-controller-manager-csr.json | cfssljson -bare {{ k8s_certs_dir }}/kube-controller-manager
    creates: "{{ item }}"
  loop:
    - "{{ k8s_certs_dir }}/kube-controller-manager.csr"
    - "{{ k8s_certs_dir }}/kube-controller-manager.pem"
    - "{{ k8s_certs_dir }}/kube-controller-manager-key.pem"
  tags: k8s_certs_generate

- name: Generate the Kube Proxy certificate and private key
  ansible.builtin.shell:
    chdir: "{{ cfssl_config_dir }}"
    executable: /bin/bash
    cmd: >
      set -eo pipefail;
      cfssl gencert \
        -ca=ca.pem \
        -ca-key=ca-key.pem \
        -config=ca-config.json \
        -profile=kubernetes \
        kube-proxy-csr.json | cfssljson -bare {{ k8s_certs_dir }}/kube-proxy
    creates: "{{ item }}"
  loop:
    - "{{ k8s_certs_dir }}/kube-proxy.csr"
    - "{{ k8s_certs_dir }}/kube-proxy.pem"
    - "{{ k8s_certs_dir }}/kube-proxy-key.pem"
  tags: k8s_certs_generate

- name: Generate the Kube Scheduler certificate and private key
  ansible.builtin.shell:
    chdir: "{{ cfssl_config_dir }}"
    executable: /bin/bash
    cmd: >
      set -eo pipefail;
      cfssl gencert \
        -ca=ca.pem \
        -ca-key=ca-key.pem \
        -config=ca-config.json \
        -profile=kubernetes \
        kube-scheduler-csr.json | cfssljson -bare {{ k8s_certs_dir }}/kube-scheduler
    creates: "{{ item }}"
  loop:
    - "{{ k8s_certs_dir }}/kube-scheduler.csr"
    - "{{ k8s_certs_dir }}/kube-scheduler.pem"
    - "{{ k8s_certs_dir }}/kube-scheduler-key.pem"
  tags: k8s_certs_generate

- name: Generate the Kubernetes API Server certificate and private key
  ansible.builtin.shell: >
    set -eo pipefail;
    cfssl gencert \
      -ca=ca.pem \
      -ca-key=ca-key.pem \
      -config=ca-config.json \
      -hostname={{ k8s_cluster_services_ip }},{{ k8s_controller_hosts | trim }},127.0.0.1,{{ k8s_hostnames }} \
      -profile=kubernetes \
      kubernetes-csr.json | cfssljson -bare {{ k8s_certs_dir }}/kubernetes
  args:
    chdir: "{{ cfssl_config_dir }}"
    executable: /bin/bash
    creates: "{{ k8s_certs_dir }}/kubernetes-key.pem"
  tags: k8s_certs_generate

- name: Generate the service account certificate and private key
  ansible.builtin.shell:
    chdir: "{{ cfssl_config_dir }}"
    executable: /bin/bash
    cmd: >
      set -eo pipefail;
      cfssl gencert \
        -ca=ca.pem \
        -ca-key=ca-key.pem \
        -config=ca-config.json \
        -profile=kubernetes \
        service-account-csr.json | cfssljson -bare {{ k8s_certs_dir }}/service-account
    creates: "{{ item }}"
  loop:
    - "{{ k8s_certs_dir }}/service-account.csr"
    - "{{ k8s_certs_dir }}/service-account.pem"
    - "{{ k8s_certs_dir }}/service-account-key.pem"
  tags: k8s_certs_generate
