---
# Path for CFSSL configuration files
cfssl_config_dir: "{{ playbook_dir }}/artifacts/cfssl-config"

# Certificate properties
cert_algo: rsa
cert_keysize: 2048
cert_expiry: 8760h
cert_names_c: BY
cert_names_l: Minsk
cert_names_st: Minsk Capital
cert_names_ou: Kubernetes on Vagrant

# These variables shall be left unchanged
k8s_cluster_services_ip: "{{ k8s_cluster_services_network | ansible.utils.ipaddr('next_usable') }}"
k8s_hostnames: kubernetes,kubernetes.default,kubernetes.default.svc,kubernetes.default.svc.cluster,kubernetes.svc.cluster.local
