---
- name: Create folder for kubeconfig files
  ansible.builtin.file:
    path: "{{ k8s_kubeconfig_dir }}"
    state: directory
    mode: "0750"
  tags: k8s_kubeconfig_create

- name: Create kubeconfig files (kubelet)
  ansible.builtin.command:
    cmd: "/tmp/{{ item }}-kubeconfig.sh"
    chdir: "{{ k8s_kubeconfig_dir }}"
    creates: "{{ item }}.kubeconfig"
  with_inventory_hostnames:
    - "{{ k8s_workers_group }}"
  tags: k8s_kubeconfig_create

- name: Create kubeconfig files (kube-proxy)
  ansible.builtin.command:
    cmd: /tmp/kube-proxy-kubeconfig.sh
    chdir: "{{ k8s_kubeconfig_dir }}"
    creates: kube-proxy.kubeconfig
  tags: k8s_kubeconfig_create

- name: Create kubeconfig files (kube-controller-manager)
  ansible.builtin.command:
    cmd: /tmp/kube-controller-manager-kubeconfig.sh
    chdir: "{{ k8s_kubeconfig_dir }}"
    creates: kube-controller-manager.kubeconfig
  tags: k8s_kubeconfig_create

- name: Create kubeconfig files (kube-scheduler)
  ansible.builtin.command:
    cmd: /tmp/kube-scheduler-kubeconfig.sh
    chdir: "{{ k8s_kubeconfig_dir }}"
    creates: kube-scheduler.kubeconfig
  tags: k8s_kubeconfig_create

- name: Create kubeconfig files (kube-admin)
  ansible.builtin.command:
    cmd: /tmp/admin-kubeconfig.sh
    chdir: "{{ k8s_kubeconfig_dir }}"
    creates: admin.kubeconfig
  tags: k8s_kubeconfig_create

- name: Generate Kubernetes encryption key
  ansible.builtin.set_fact:
    k8s_encryption_key: "{{ lookup('ansible.builtin.password', '/dev/null', chars=['printable', 'whitespace'], length=32) | ansible.builtin.b64encode }}"
  tags: k8s_kubeconfig_create

- name: Create Kubernetes encryption config
  ansible.builtin.template:
    src: encryption-config.yaml.j2
    dest: "{{ k8s_kubeconfig_dir }}/encryption-config.yaml"
    mode: "0600"
  tags: k8s_kubeconfig_create
